(define (problem p)
        (:domain lighUp-akari)
    
	(:init
		(count-zero c-0-2)
(count-zero c-3-4)
(count-zero c-4-2)
(count-zero c-6-3)
(count-zero c-6-6)

	)

	(:goal (and 
		(or (iluminado-linha l1) (iluminado-coluna c1))
		(or (iluminado-linha l1) (iluminado-coluna c2))
(count-two c-0-2) 		(or (iluminado-linha l2) (iluminado-coluna c6))
		(or (iluminado-linha l2) (iluminado-coluna c7))
		(or (iluminado-linha l2) (iluminado-coluna c9))
		(or (iluminado-linha l2) (iluminado-coluna c11))
		(or (iluminado-linha l3) (iluminado-coluna c1))
		(or (iluminado-linha l3) (iluminado-coluna c2))
		(or (iluminado-linha l3) (iluminado-coluna c4))
		(or (iluminado-linha l3) (iluminado-coluna c6))
		(or (iluminado-linha l3) (iluminado-coluna c7))
		(or (iluminado-linha l3) (iluminado-coluna c9))
		(or (iluminado-linha l3) (iluminado-coluna c11))
		(or (iluminado-linha l4) (iluminado-coluna c1))
		(or (iluminado-linha l4) (iluminado-coluna c2))
		(or (iluminado-linha l4) (iluminado-coluna c4))
		(or (iluminado-linha l4) (iluminado-coluna c6))
		(or (iluminado-linha l4) (iluminado-coluna c7))
		(or (iluminado-linha l5) (iluminado-coluna c11))
		(or (iluminado-linha l6) (iluminado-coluna c1))
		(or (iluminado-linha l7) (iluminado-coluna c4))
		(or (iluminado-linha l7) (iluminado-coluna c6))
(count-zero c-3-4) 		(or (iluminado-linha l8) (iluminado-coluna c10))
		(or (iluminado-linha l8) (iluminado-coluna c11))
		(or (iluminado-linha l9) (iluminado-coluna c1))
		(or (iluminado-linha l9) (iluminado-coluna c3))
(count-two c-4-2) 		(or (iluminado-linha l10) (iluminado-coluna c6))
		(or (iluminado-linha l10) (iluminado-coluna c8))
		(or (iluminado-linha l10) (iluminado-coluna c10))
		(or (iluminado-linha l10) (iluminado-coluna c11))
		(or (iluminado-linha l11) (iluminado-coluna c1))
		(or (iluminado-linha l11) (iluminado-coluna c3))
		(or (iluminado-linha l11) (iluminado-coluna c5))
		(or (iluminado-linha l11) (iluminado-coluna c6))
		(or (iluminado-linha l11) (iluminado-coluna c8))
		(or (iluminado-linha l11) (iluminado-coluna c10))
		(or (iluminado-linha l11) (iluminado-coluna c11))
		(or (iluminado-linha l12) (iluminado-coluna c1))
		(or (iluminado-linha l12) (iluminado-coluna c3))
		(or (iluminado-linha l12) (iluminado-coluna c5))
(count-zero c-6-3) 		(or (iluminado-linha l13) (iluminado-coluna c8))
		(or (iluminado-linha l13) (iluminado-coluna c10))
(count-two c-6-6) 		)
	)
)
