(define (problem p)
    (:domain lighUp-akari)


	(:init
		(count-zero c-0-2) (count-zero c-3-4) (count-zero c-4-2) (count-zero c-6-3) (count-zero c-6-6) 
	)

	(:goal (and 
		(iluminado c-0-0) 
		(iluminado c-0-1) 
		(count-two c-0-2) 
		(iluminado c-0-3) 
		(iluminado c-0-4) 
		(iluminado c-0-5) 
		(iluminado c-0-6) 
		(iluminado c-1-0) 
		(iluminado c-1-1) 
		(iluminado c-1-2) 
		(iluminado c-1-3) 
		(iluminado c-1-4) 
		(iluminado c-1-5) 
		(iluminado c-1-6) 
		(iluminado c-2-0) 
		(iluminado c-2-1) 
		(iluminado c-2-2) 
		(iluminado c-2-3) 
		(iluminado c-2-4) 
		
		(iluminado c-2-6) 
		(iluminado c-3-0) 
		
		(iluminado c-3-2) 
		(iluminado c-3-3) 
		(count-zero c-3-4) 
		(iluminado c-3-5) 
		(iluminado c-3-6) 
		(iluminado c-4-0) 
		(iluminado c-4-1) 
		(count-two c-4-2) 
		(iluminado c-4-3) 
		(iluminado c-4-4) 
		(iluminado c-4-5) 
		(iluminado c-4-6) 
		(iluminado c-5-0) 
		(iluminado c-5-1) 
		(iluminado c-5-2) 
		(iluminado c-5-3) 
		(iluminado c-5-4) 
		(iluminado c-5-5) 
		(iluminado c-5-6) 
		(iluminado c-6-0) 
		(iluminado c-6-1) 
		(iluminado c-6-2) 
		(count-zero c-6-3) 
		(iluminado c-6-4) 
		(iluminado c-6-5) 
		(count-two c-6-6) 
		)))
